name: Continues Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Build stage
       run: echo " App is building"

  access_vars:
   runs-on: ubuntu-latest
   steps:
     - name: Access variable
       run: echo "My name is ${{vars.MY_NAME}}"

  access_secret:
   runs-on: ubuntu-latest
   steps:
     - name: Access secret
       run: echo "My name is ${{secrets.TEST_SECRET}}"

       
