name: Continues Integration
on: workflow_dispatch
jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
     - name: Printing Hello_world
       run: echo "Hello world"
       
     - name: Multi line strings
       run: |
         echo "first Line"
         echo "second Line"
         echo "third Line"
       
