name: Inputs Demo
on:
  workflow_dispatch:
    inputs:
      first_input:
       description: first input to select
       type: choice  
       required: true
       default: dev
       options:
        - dev
        - stage
        - prod

jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "Deploying the application to ${{inputs.first_input}}"
       
